version: '3.8'

services:
  # This config is for MongoDB v4
  # It's a Replica Set (required for Prisma Client)
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 4
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      # Use "mongosh" instead of "mongo" for v5+
      MONGO_COMMAND: 'mongo'
    ports:
      - '27017:27017'
    restart: unless-stopped
    healthcheck:
      # Use "mongosh" instead of "mongo" for v5+
      test:
        [
          'CMD',
          'mongo',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
